version: "3"

services:

  # Preparation for generated services started
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    hostname: mongodb
    networks:
      data-loading:
        aliases:
          - mondodb
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "512M"

  cassandra:
    image: cassandra
    container_name: cassandra
    hostname: cassandradb
    networks:
      data-loading:
        aliases:
          - cassandradb
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "8G"

  nasa_data_loader:
    image: nasa_data_loader
    container_name: nasa_dataloader
    depends_on:
      - cassandra
    networks:
      data-loading:
        aliases:
          - nasa_data_loader
    environment:
      - NASA_DB_HOST=cassandradb
      - NASA_DB_PORT=9042
      - NASA_DB_KEYSPACE=nasa
      - NASA_SOURCE_URL=https://images-api.nasa.gov/search?q=nasa&media_type=image
      - NASA_DB_REPLICATION_FACTOR=1
      - WAITING_TO_CONNECT_PERIOD_SEC=600
    build:
      ./nasa
    command:
      python ./nasa_loader.py
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "256M"

  news_data_loader:
    image: news_data_loader
    container_name: news_dataloader
    depends_on:
      - mongo
    networks:
      data-loading:
        aliases:
          - news_data_loader
    build:
      ./news
    command:
      python ./news_loader.py
    environment:
      - NEWS_DB_HOST=mongo
      - NEWS_DB_PORT=27017
      - NEWS_DB_COLLECTION_NAME=news
      - NEWS_SOURCE_URL=https://newsapi.org/v2/everything?q=nasa&from={}&to={}&apiKey={}
      - NEWS_API_KEY=adf243e64cf34f698088d4df49fc9734
      - NEWS_DAYS_AGO=7
      - NEWS_CONNECT_TIMEOUT_MS=600000
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "256M"

# Preparation finished

# Run generated News Service
  newsservice:
    image: nickyklaus/newsservice:latest
    container_name: newsservice
    depends_on:
      - mongo
    networks:
      data-loading:
        aliases:
          - newsservice
    hostname: newsservice
    ports:
      - 8080:8080
    environment:
      - NEWS_DB_HOST=mongo
      - NEWS_DB_PORT=27017
      - NEWS_DB_NAME=news
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "512M"

# Run generated Nasa Service
  nasaservice:
    image: nickyklaus/nasaservice:latest
    container_name: nasaservice
    depends_on:
      - cassandra
    networks:
      data-loading:
        aliases:
          - nasaservice
    hostname: nasaservice
    ports:
      - 8090:8090
    environment:
      - NASA_DB_HOST=cassandradb
      - NASA_DB_PORT=9042
      - NASA_DB_KEYSPACE=nasa
      - NASA_DB_LOCAL_DC=datacenter1
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1G"

networks:
  data-loading:
    driver: "bridge"